version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      ALGORITHM: aes-256-cbc
      KEY: 60a6b8f5e6454b6a2c7d2c5b1d4f4e3e5a7c5f8e7d6c9f0b0a8c4b2f5e5a9b6e3
      IV: c8b4f84d0a8e7b1f2e3c4d5e6f7a8b9c
      SECTET_KEY: jaiShreeRam
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: passwordManager
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: passwordManager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
